### ISSUE TITLE
Setting the SUPERUSER_REALM makes admin access unusable

### ISSUE THREAD

**Issue by camelusferus** [kheeklab/privacyidea-docker#108]
**Describe the bug**
When setting the ``SUPERUSER_REALM`` environment variable, it is not possible to login to the administrative view.

**To Reproduce**
1. Set up a container without the ``SUPERUSER_REALM`` environment variable, and verify its working.
2. (_optional_) Create a second realm in the admin panel, you want to use for administrative purposes, e.g. an 'api' for automating PI using their rest API.
3. Setting the env variable ``SUPERUSER_REALM=['administrator','api'] `` and restart the container
4. When logging in with an user in the admin realm, the user doesn't have the admin UI anymore, but only the user UI.

Also trying ``"['administrator','api']"`` or ``\['administrator','api'\]`` hasn't helped.

As a dirty hack: If you set ``SUPERUSER_REALM = ['administrator','api']`` by hand in the ``/etc/privacyidea/pi.cfg`` file inside the container, it works.

**Expected behavior**
Login with a user in the admin realm still works and you have a working admin realm, for which e.g. in the policy section of the configuration tab, you could select in admin policies the realm 'api'.

**Environments (please complete the following information):**
 - OS: Debian 12 hosting the Container
 - Browser: Firefox 115ESR
 - PI version or image tag v3.9-patch1
 - Database postgresql

**Additional context**
I think, the problem lies in the ``rootfs/opt/templates/pi-config.template`` in line 15 as the environ to my knowledge returns strings and the default value is an list.

**Comment by mr-ssd** [comment]
@camelusferus thank you for reporting the issue and sorry for the late response. I'll check on this.

**Comment by mr-ssd** [comment]
@camelusferus please verify if the latest release fix the issue.

**Comment by camelusferus** [comment]
@mr-ssd I am sorry, but all builds from today on the docker hub wont even start in my environment.

All result/errors I got from a docker-compose setup with the tag ``v3.9.1-d1.1.0``. If I dont set a SUPERUSER_REALM, the pi_cfg script crashes on the trimming of quotes on the default values a list:
```
privacyidea_1  | Traceback (most recent call last):
privacyidea_1  |   File "/opt/privacyidea/bin/pi-manage", line 113, in <module>
privacyidea_1  |     app = create_app(config_name='production', silent=SILENT)
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/app.py", line 133, in create_app
privacyidea_1  |     app.config.from_pyfile(config_file, silent=True)
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask/config.py", line 132, in from_pyfile
privacyidea_1  |     exec(compile(config_file.read(), filename, "exec"), d.__dict__)
privacyidea_1  |   File "/etc/privacyidea/pi.cfg", line 22, in <module>
privacyidea_1  |     if SUPERUSER_REALM.startswith(delimiter) and SUPERUSER_REALM.endswith(delimiter):
privacyidea_1  | AttributeError: 'list' object has no attribute 'startswith'
```

When I set a list of SUPERUSER_REALM's, the pi-manage script crashes, by a typo in then sqlalchemy URL:

```
privacyidea_1  | Traceback (most recent call last):
privacyidea_1  |   File "/opt/privacyidea/bin/pi-manage", line 1739, in <module>
privacyidea_1  |     manager.run()
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_script/__init__.py", line 417, in run
privacyidea_1  |     result = self.handle(argv[0], argv[1:])
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_script/__init__.py", line 386, in handle
privacyidea_1  |     res = handle(*args, **config)
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_script/commands.py", line 216, in __call__
privacyidea_1  |     return self.run(*args, **kwargs)
privacyidea_1  |   File "/opt/privacyidea/bin/pi-manage", line 589, in create_tables
privacyidea_1  |     print(db)
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1115, in __repr__
privacyidea_1  |     self.engine.url if self.app or current_app else None
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
privacyidea_1  |     return self.get_engine()
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
privacyidea_1  |     return connector.get_engine()
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 592, in get_engine
privacyidea_1  |     sa_url = make_url(uri)
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
privacyidea_1  |     return _parse_url(name_or_url)
privacyidea_1  |   File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 799, in _parse_url
privacyidea_1  |     raise exc.ArgumentError(
privacyidea_1  | sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string '=postgresql+psycopg2://DB_USER_REDACTED:DB_PW_REDACTED@DB_HOST_REDACTED:5432/DB_NAME_REDACTED'
```

**Comment by mr-ssd** [comment]
@camelusferus could please share your docker-compose you we can test it on the same environment? Meanwhile, if you have an idea to fix it that is also welcome.

for **SUPERUSER_REALM** please set in value in comma separated. `SUPERUSER_REALM=administrator,api`

**Comment by mr-ssd** [comment]
@camelusferus thank you for the PR and please consider starring ⭐ to help it reach more people and get more feedback like this.
