### ISSUE TITLE
privacyidea_entrypoint.sh is missing

### ISSUE THREAD

**Issue by azeemdin** [kheeklab/privacyidea-docker#118]
**Describe the bug**
After following the intstruction I have created a docker image using make build command

khalibre/privacyidea:dev

But when I try to run it using make run. I am getting this error

`[FATAL tini (7)] exec /usr/local/bin/privacyidea_entrypoint.sh failed: No such file or directory`

**To Reproduce**
1. Clone directory
2. make build
3. make run

**Expected behavior**
A container with privacyidea must be running

**Environments (please complete the following information):**
 - OS: Windows 11 with cygwin
 - Docker Desktop 4.27.1

**Additional context**
I have been trying to run privacyidea in openshift cluster using helmchart. I tried the khalibre/privacyidea:latest image from docker hub. But that gives me below error, so i am trying to build image by myself
`mkdir: cannot create directory ‘/etc/nginx/certs’: Permission denied`

**Comment by mr-ssd** [comment]
`[FATAL tini (7)] exec /usr/local/bin/privacyidea_entrypoint.sh failed: No such file or directory` I will take a look on this.

`mkdir: cannot create directory ‘/etc/nginx/certs’: Permission denied` this might due to openshift strict permission on privilege. I haven't been tested on openshift.

**Comment by mr-ssd** [comment]
@azeemdin `[FATAL tini (7)] exec /usr/local/bin/privacyidea_entrypoint.sh failed: No such file or directory` might cause might by missing execute permission on script files when checkout on Windows.
Could you try on add  `RUN chmod +x /usr/local/bin/*.sh` to **Dockerfile** and try build again

**Comment by mr-ssd** [comment]
OpenShift will by default run containers as a non root user. As a result, the application can fail if it requires it runs as root. I don't have OpenShift cluster to testing so I might need your help on testing.

**Comment by azeemdin** [comment]
Thanks @mr-ssd  for the reply. You are right about the permissions. I will have to look into details how to update the configuration to make it run.

Meanwhile I have solved my problem using another [repository](https://github.com/gpappsoft/privacyidea-docker). Thanks for your contribution, time and support for the community.
