### ISSUE TITLE
mistype in export syntax

### ISSUE THREAD

**Issue by gitalexch** [kheeklab/privacyidea-docker#160]
**Describe the bug**
incorrect export syntax

**To Reproduce**

after startup:

```
[INFO] Using postgresql...
/usr/local/bin/configure_privacyidea.sh: line 111: export: `/opt/privacyidea': not a valid identifier
```

**Comment by gitalexch** [comment]
PR: https://github.com/Khalibre/privacyidea-docker/pull/159
need to be backported together with https://github.com/Khalibre/privacyidea-docker/pull/157 to 3.9.x tags

**Comment by gitalexch** [comment]
autotests of adding files and scripts are urgently needed in pipelines before publishing images. Unfortunately I am not familiar with pipelines :(

**Comment by mr-ssd** [comment]
for testing you can start with https://github.com/GoogleContainerTools/container-structure-test

**Comment by gitalexch** [comment]
Thanks but I didn't find there what I want:
I want to test if container could run after changes and is not dying after startup, and files of files and scripts  exits on running container file system after cp in privacyidea_entrypoint.sh script

I have found something like at github action: zethuman/healthcheck@v0.0.1, but I am absolutely NOT sure that it is exactly what we need....

**Comment by mr-ssd** [comment]
Yeah we'll check what we can do but I'll close this issue and create a new discussion for that
