### ISSUE TITLE
This script must be run inside a python virtual environment!

### ISSUE THREAD

**Issue by michimau** [kheeklab/privacyidea-docker#22]
dear, thank you for the fantastic image.
a number of scripts in "/usr/local/bin" do not work outside a python virtual environment.

I do not see you have created one. how do you workaround?

**Comment by mr-ssd** [comment]
Hi @michimau,

Thank you for reporting the issue. Could you please specify or list scripts that do not work outside a python virtual environment? or step to reproduce is very helpful.

Yes, you're correct. I don't create a virtual env in this image.

Cheer,
Sida

**Comment by mr-ssd** [comment]
virtual environment in #25
