### ISSUE TITLE
The postgres module pg8000 is throwing an error 

### ISSUE THREAD

**Issue by cmbyrne** [kheeklab/privacyidea-docker#32]
When attempting to create the privacyidea database to pg8000 module is throwing an error.  Switching to psycopg2 solves the issue. However you have to install psycopg2-binary instead of psycopg2.

**Comment by mr-ssd** [comment]
@cmbyrne sorry about the issue. I haven't tested with the PostgreSQL database engine. Will take a took about this. 
Cheer

**Comment by mr-ssd** [comment]
@cmbyrne anyway could you share the error message.

**Comment by cmbyrne** [comment]
Sorry didn't save the stack trace but it was
TypeError: expected bytes, str found

**Comment by mr-ssd** [comment]
@cmbyrne found the root cause https://stackoverflow.com/a/64519602. It works after pinning to version 1.16.5. I'm considering switching to another DBAPI  supported by [SQLAlchemy](https://stackoverflow.com/a/64519602).

**Comment by mr-ssd** [comment]
Fix in #33 
Thank @cmbyrne for the report.
