### ISSUE TITLE
Update PI and Python

### ISSUE THREAD

**Issue by dronenb** [kheeklab/privacyidea-docker#49]
Python 3.8.14 was released on Sept. 14 (see [changelog](https://docs.python.org/release/3.8.14/whatsnew/changelog.html)). Additionally, privacyIDEA 3.7.3 was released on August 1. I think the dockerfile should be updated to include these new versions.

**Comment by mr-ssd** [comment]
Hi @dronenb thank you for reporting the update. I'll check it out. By the way, you can submit your PR if you like.
Cheer,

**Comment by mr-ssd** [comment]
@dronenb issue has been fix in #51
