### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by maxstaubach** [kheeklab/privacyidea-docker#60]
Hello,
thank you very much for creating the image.
Unfortunately I have a problem using the image.
I work with Docker Desktop and windows 10.
I have attached the compose file and log.

No error message is thrown to help me. Is there a debug mode on startup that shows more information?
Thanks a lot!
[log.txt](https://github.com/Khalibre/privacyidea-docker/files/10871301/log.txt)
[docker-compose.txt](https://github.com/Khalibre/privacyidea-docker/files/10871302/docker-compose.txt)

**Comment by mr-ssd** [comment]
Hi @maxstaubach 

That is an issue I just discovered last week too. I miss documenting how to set up with existing data. To solve your issue please just set Docker ENV with `PI_SKIP_BOOTSTRAP=true` to your docker-compose file. By default `PI_SKIP_BOOTSTRAP=false` allows PI to set up all required configurations. 

I'll update the document and also the error message later to address this issue.

Cheer!
