### ISSUE TITLE
permission of /tmp/uwsgi.sock

### ISSUE THREAD

**Issue by brammeleman** [kheeklab/privacyidea-docker#62]
I'm getting a 502 Bad Gateway when running the docker-compose.yml with podman.
Version: v3.8.1-p3.8.16

Looks like a permission problem on `/tmp/uwsgi.sock`

```
podman-compose exec privacyidea cat /var/log/nginx/error.log
```
shows these lines:
```
2023/03/13 13:18:24 [crit] 169#169: *1 connect() to unix:///tmp/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.89.16.9, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "localhost:45655"
```

When I run a `chmod go+rw /tmp/uwsgi.sock` in the container all works fine afterwards. That's just to see where the issue is... some permission problem. Did not yet have a look on how to solve it....

**Comment by mr-ssd** [comment]
@brammeleman thank you for reporting the issue. I'll check on this.

**Comment by mr-ssd** [comment]
Anyway, could share with me the docker image tag version you are using?

**Comment by brammeleman** [comment]
I built the docker image with:
```
podman build -t khalibre/privacyidea:dev .
```
using the version just released (v3.8.1-p3.8.16).

**Comment by mr-ssd** [comment]
only tested with docker build will try with podman  
thank

**Comment by brammeleman** [comment]
Using a network port instead of a socket-file works for me. (not tested with docker ;-)).
``` diff
--- a/rootfs/etc/uwsgi/uwsgi.ini
+++ b/rootfs/etc/uwsgi/uwsgi.ini
@@ -1,9 +1,7 @@
 [uwsgi]
 wsgi-file=/opt/privacyidea/etc/privacyidea/privacyideaapp.wsgi
 buffer-size=8192
-socket = /tmp/uwsgi.sock
-chown-socket = www-data:www-data
-chmod-socket = 664
+socket = 127.0.0.1:8000
 # Graceful shutdown on SIGTERM, see https://github.com/unbit/uwsgi/issues/849#issuecomment-118869386
 hook-master-start = unix_signal:15 gracefully_kill_them_all
 need-app = true
```

``` diff
--- a/rootfs/opt/templates/nginx-pi-ssl.conf.template
+++ b/rootfs/opt/templates/nginx-pi-ssl.conf.template
@@ -17,6 +17,6 @@ server {
     location / {
 
         include uwsgi_params;
-        uwsgi_pass unix:///tmp/uwsgi.sock;
+        uwsgi_pass 127.0.0.1:8000;
     }
 }
```
and ditto for the other nginx template.
This would also allow for having a separate nginx service in `docker-compose.yml`.

**Comment by mr-ssd** [comment]
yeah, I'm experimenting to remove nginx from this image, so we have the choice to use another proxy like Traefik or the other.
