### ISSUE TITLE
tree not installed in container

### ISSUE THREAD

**Issue by consulion** [kheeklab/privacyidea-docker#66]
When starting the container i get the following message:
`/usr/local/bin/start_privacyidea.sh: line 83: tree: command not found`

**Comment by mr-ssd** [comment]
Hi @consulion 

Could you please detail your step on how to reproduce that error since I could not reproduce it on my side?
Did you build your own image or use the image from the Docker hub? And with version?

Thank

**Comment by consulion** [comment]
Hi, my start script has the following content:

```
docker run --restart=always \
 --name privacyideavenus \
 -p 8075:443 \
 --net=dockernet \
 -v /docker/data/privacyidea:/mnt/privacyidea \
 -e DB_VENDOR='mysql' \
 -e DB_USER='privacyidea' \
 -e DB_NAME='privacyidea' \
 -e DB_PASSWORD='<redacted>' \
 -e DB_HOST='mysqlvenus' \
 -e PI_ADMIN_USER='admin' \
 -e PI_ADMIN_PASSWORD='<redacted>' \
 -e NGINX_LISTEN_PORT=8080 \
 -e NGINX_LISTEN_PORT=443 \
 -e NGINX_SSL_ENABLED=false \
 -e SECRET_KEY='<redacted>' \
 -e PI_PEPPER='<redacted>' \
 -d khalibre/privacyidea

```
it seems to be that 'tree' isn't available in the underlaying container.
For now i have a workaround to inject `apt-get install -y tree` before the actual entrypoint and it works

**Comment by mr-ssd** [comment]
The latest tag has not been tested. You should use the image with a specific tag e.g ` khalibre/privacyidea:v3.8.1-p3.8.16-r2`

**Comment by mr-ssd** [comment]
I'll take a look to make sure the latest tag is synced and tested.

**Comment by consulion** [comment]
> The latest tag has not been tested. You should use the image with a specific tag e.g ` khalibre/privacyidea:v3.8.1-p3.8.16-r2`

unfortunately this also results in the same error, i tried all version tags since 3.7.
since it happens in 

```
function prestart_privacyidea {

    # Copy files from mounted directory to PI_HOME
    if [ -d "${PI_MOUNT_DIR}/files" ] && [ "$(ls -A "${PI_MOUNT_DIR}/files")" ]; then
        echo "[privacyIDEA] Copying files from ${PI_MOUNT_DIR}/files:"
        echo ""
        tree --noreport "${PI_MOUNT_DIR}/files"
        echo ""
        echo "[privacyIDEA] ... into ${PI_HOME}."
        cp -r "${PI_MOUNT_DIR}/files"/* "${PI_HOME}"
        echo ""
    else
        echo "[privacyIDEA] The directory ${PI_MOUNT_DIR}/files does not exist or is empty. Copy any files to this directory to have them copied to ${PI_HOME} before privacyIDEA starts."
        echo ""
    fi

```
in start_privacyidea.sh, it should only occur if there are files in the ${PI_MOUNT_DIR}/files directory.

**Comment by consulion** [comment]
#67
